[package]
name = "voxel-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
gl33 = "0.2.1"
beryllium = "0.13.3"
imagine = "0.5.3"
glam = { version = "0.30.9", features = ["bytemuck", "glam-assert", "serde"] }
image = "0.25.9"
num_enum = "0.7.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
rand = "0.9.2"
glam-traits = "0.3.1"
noise = "0.9.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
